# App
spring.application.name=monetization-backend
server.port=${PORT:8080}
admin.api.key= sk_admin_local_test_key
mpesa.mock = true

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# ===============================
# MPESA SANDBOX CONFIG
# ===============================

mpesa.base-url=${MPESA_BASE_URL}
mpesa.consumer-key=${MPESA_CONSUMER_KEY}
mpesa.consumer-secret=${MPESA_CONSUMER_SECRET}
mpesa.short-code=${MPESA_SHORT_CODE}
mpesa.passkey=${MPESA_PASSKEY}
mpesa.callback-url=${MPESA_CALLBACK_URL}