# App
spring.application.name=monetization-backend
server.port=8080
admin.api.key= sk_admin_local_test_key
mpesa.mock = true
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/monetization_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# ===============================
# MPESA SANDBOX CONFIG
# ===============================

mpesa.base-url=https://sandbox.safaricom.co.ke
mpesa.consumer-key=${MPESA_CONSUMER_KEY}
mpesa.consumer-secret=${MPESA_CONSUMER_SECRET}
mpesa.passkey=${MPESA_PASSKEY}
mpesa.shortcode=174379
mpesa.callback-url= https://unregressive-ilse-obclavate.ngrok-free.dev/api/v1/webhooks/mpesa/callback